#!/usr/bin/env python3
"""Rebuild the TOTEM keymap from the checked-in original QMK Configurator export."""
import json
import re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
source = json.loads((ROOT / 'reference/qmk-keymap.json').read_text())
# Read left-to-right physical coordinates in the original LAYOUT_5x6_5.
indices = [*range(13, 23), *range(25, 35), None, *range(37, 47), None, *range(50, 56)]
assert len(indices) == 38
names = ['BASE', 'NAV', 'NUM', 'FUN', 'MOUSE']
alias = {'SCLN':'SEMI','COMM':'COMMA','SLSH':'FSLH','SPC':'SPACE','ENT':'RET','BSPC':'BSPC',
'BSLS':'BSLH','LBRC':'LBKT','RBRC':'RBKT','MINS':'MINUS','GRV':'GRAVE','QUOT':'SQT','EQL':'EQUAL',
'RGHT':'RIGHT','PGDN':'PG_DN','PGUP':'PG_UP','SLEP':'SYS_SLEEP','VOLD':'C_VOL_DN','VOLU':'C_VOL_UP',
'MPLY':'C_PP','LCTL':'LCTRL','RCTL':'RCTRL','LSFT':'LSHFT','RSFT':'RSHFT'}
mods = {'LCTL':'LCTRL','LALT':'LALT','LSFT':'LSHFT','LGUI':'LGUI',
'RGUI':'RGUI','RSFT':'RSHFT','RALT':'RALT','RCTL':'RCTRL'}
mouse = {'MS_LEFT':'&mmv MOVE_LEFT','MS_DOWN':'&mmv MOVE_DOWN','MS_UP':'&mmv MOVE_UP',
'MS_RGHT':'&mmv MOVE_RIGHT','MS_WHLR':'&msc SCRL_RIGHT','MS_WHLU':'&msc SCRL_UP',
'MS_WHLD':'&msc SCRL_DOWN','MS_WHLL':'&msc SCRL_LEFT','MS_BTN1':'&mkp LCLK',
'MS_BTN2':'&mkp RCLK','MS_BTN3':'&mkp MCLK','MS_ACL0':'&mo 5','MS_ACL2':'&mo 6'}
def key(k):
    k = k.removeprefix('KC_')
    return 'N'+k if k.isdigit() else alias.get(k,k)
def convert(k):
    if k == 'KC_NO': return '&none'
    if k == 'QK_BOOT': return '&bootloader'
    if k in mouse: return mouse[k]
    if m := re.fullmatch(r'(LCTL|LALT|LSFT|LGUI|RGUI|RSFT|RALT|RCTL)_T\((KC_\w+)\)', k):
        mod, code = m.groups()
        return f'&hm{mod[0].lower()} {mods[mod]} {key(code)}'
    if m := re.fullmatch(r'LT\((\d+),(KC_\w+)\)', k):
        layer, code = m.groups()
        return f'&lt {layer} {key(code)}'
    if m := re.fullmatch(r'(LGUI|RGUI|RSG)\((KC_\w+)\)', k):
        mod, code = m.groups()
        macro = {'LGUI':'LG','RGUI':'RG','RSG':'RS'}[mod]
        inner = f'RG({key(code)})' if mod == 'RSG' else key(code)
        return f'&kp {macro}({inner})'
    if k.startswith('KC_'):
        z = key(k)
        autoshift = (len(z)==1 and z.isalpha()) or bool(re.fullmatch('N[0-9]',z)) or z in {
            'SEMI','COMMA','DOT','FSLH','BSLH','LBKT','RBKT','MINUS','GRAVE','SQT','EQUAL','TAB'}
        return f'AS({z})' if autoshift else f'&kp {z}'
    raise ValueError(k)
header = '''// Generated by scripts/convert_qmk.py. See MIGRATION.md for behavioral differences.
#include <behaviors.dtsi>
#include <dt-bindings/zmk/keys.h>
#include <dt-bindings/zmk/bt.h>
#include <dt-bindings/zmk/outputs.h>
#include <dt-bindings/zmk/pointing.h>
#define AS(k) &as LS(k) k

&lt {
    tapping-term-ms = <175>;
    flavor = "hold-preferred";
    retro-tap;
};

/ {
    behaviors {
        as: auto_shift {
            compatible = "zmk,behavior-hold-tap";
            #binding-cells = <2>;
            bindings = <&kp>, <&kp>;
            flavor = "tap-preferred";
            tapping-term-ms = <175>;
            quick-tap-ms = <0>;
            display-name = "Auto Shift 175ms";
        };
'''
# Exclude only home-row mod keys from the SAME hand; allow same-hand plain keys.
# ZMK positional hold-tap still differs from QMK permissive-hold on excluded keys.
for hand, excluded in [('l',set(range(10,14))),('r',set(range(16,20)))]:
    positions = ' '.join(str(i) for i in range(38) if i not in excluded)
    header += f'''        hm{hand}: home_row_{hand} {{
            compatible = "zmk,behavior-hold-tap";
            #binding-cells = <2>;
            bindings = <&kp>, <&kp>;
            flavor = "hold-preferred";
            tapping-term-ms = <175>;
            retro-tap;
            retro-shift-ms = <500>;
            hold-trigger-key-positions = <{positions}>;
            display-name = "Home row {hand.upper()}";
        }};
'''
header += '    };\n    keymap {\n        compatible = "zmk,keymap";\n'
layers=[]
for n, layer in enumerate(source['layers']):
    assert len(layer)==62
    keys = [convert(layer[i]) if i is not None else '&none' for i in indices]
    keys[20] = '&bt BT_CLR' if n==3 else '&bt BT_NXT'
    keys[31] = '&out OUT_TOG' if n==3 else '&studio_unlock'
    layers.append(keys)
# Speed overlays replace only directions; other bindings fall through to MOUSE.
for speed in [200,1200]:
    keys = ['&trans']*38
    for pos, axis, amount in [(16,'X',-speed),(17,'Y',speed),(18,'Y',-speed),(19,'X',speed)]:
        keys[pos] = f'&mmv MOVE_{axis}({amount})'
    layers.append(keys)
for name, keys in zip(names+['MOUSE_SLOW','MOUSE_FAST'],layers):
    header += f'        {name.lower()} {{\n            display-name = "{name}";\n            bindings = <\n'
    for start,end in [(0,10),(10,20),(20,32),(32,38)]:
        header += '                '+'  '.join(f'{s:<21}' for s in keys[start:end]).rstrip()+'\n'
    header += '            >;\n        };\n'
header += '    };\n};\n'
(ROOT/'config/totem.keymap').write_text(header)
print('Generated 5 source layers + 2 mouse-speed overlays, 38 positions each.')
